using FluentAssertions;
using FluentValidation.TestHelper;
using Microsoft.EntityFrameworkCore;
using NetcoreHRIS.Modules.LeaveRequests;
using NetcoreHRIS.Modules.LeaveRequests.Dtos;
using NetcoreHRIS.Modules.LeaveRequests.Validators;
using NetcoreHRIS.Tests.Helpers;

namespace NetcoreHRIS.Tests.Unit.LeaveRequests;

public class LeaveRequestsServiceTests
{
    [Fact]
    public async Task Create_ValidRequest_ReturnsAutoGeneratedRequestNo()
    {
        await using var db = DbContextFactory.Create();
        await EntityBuilder.SeedDefaultDataAsync(db);
        var svc = new LeaveRequestsService(db);

        var result = await svc.CreateAsync(new CreateLeaveRequestRequest(
            EntityBuilder.Employee1Id,
            EntityBuilder.AnnualLeaveId,
            new DateOnly(2026, 1, 10),
            new DateOnly(2026, 1, 12),
            "Family event"), CancellationToken.None);

        result.RequestNo.Should().StartWith("LR-");
        result.EmployeeId.Should().Be(EntityBuilder.Employee1Id);
    }

    [Fact]
    public async Task GetById_ValidId_ReturnsLeaveRequest()
    {
        await using var db = DbContextFactory.Create();
        await EntityBuilder.SeedDefaultDataAsync(db);
        var leaveRequest = new Entities.LeaveRequest
        {
            RequestNo = "LR-20260101-ABC",
            EmployeeId = EntityBuilder.Employee1Id,
            LeaveMasterId = EntityBuilder.AnnualLeaveId,
            FromDate = new DateOnly(2026, 1, 10),
            ToDate = new DateOnly(2026, 1, 12),
            Reason = "Family event"
        };
        db.LeaveRequests.Add(leaveRequest);
        await db.SaveChangesAsync();

        var svc = new LeaveRequestsService(db);
        var result = await svc.GetByIdAsync(leaveRequest.Id, CancellationToken.None);

        result.Id.Should().Be(leaveRequest.Id);
        result.RequestNo.Should().Be("LR-20260101-ABC");
    }

    [Fact]
    public async Task Update_ChangesReason()
    {
        await using var db = DbContextFactory.Create();
        await EntityBuilder.SeedDefaultDataAsync(db);
        var leaveRequest = new Entities.LeaveRequest
        {
            RequestNo = "LR-20260101-DEF",
            EmployeeId = EntityBuilder.Employee1Id,
            LeaveMasterId = EntityBuilder.AnnualLeaveId,
            FromDate = new DateOnly(2026, 1, 10),
            ToDate = new DateOnly(2026, 1, 12),
            Reason = "Family event"
        };
        db.LeaveRequests.Add(leaveRequest);
        await db.SaveChangesAsync();

        var svc = new LeaveRequestsService(db);
        var result = await svc.UpdateAsync(leaveRequest.Id,
            new UpdateLeaveRequestRequest(null, null, null, null, "Updated reason", null), CancellationToken.None);

        result.Reason.Should().Be("Updated reason");
    }

    [Fact]
    public async Task Delete_SoftDeletesLeaveRequest()
    {
        await using var db = DbContextFactory.Create();
        await EntityBuilder.SeedDefaultDataAsync(db);
        var leaveRequest = new Entities.LeaveRequest
        {
            RequestNo = "LR-20260101-GHI",
            EmployeeId = EntityBuilder.Employee1Id,
            LeaveMasterId = EntityBuilder.AnnualLeaveId,
            FromDate = new DateOnly(2026, 1, 10),
            ToDate = new DateOnly(2026, 1, 12),
            Reason = "Family event"
        };
        db.LeaveRequests.Add(leaveRequest);
        await db.SaveChangesAsync();

        var svc = new LeaveRequestsService(db);
        await svc.DeleteAsync(leaveRequest.Id, CancellationToken.None);

        var deleted = await db.LeaveRequests.IgnoreQueryFilters().FirstAsync(x => x.Id == leaveRequest.Id);
        deleted.IsDeleted.Should().BeTrue();
    }
}

public class LeaveRequestValidatorTests
{
    private readonly CreateLeaveRequestRequestValidator _createValidator = new();
    private readonly UpdateLeaveRequestRequestValidator _updateValidator = new();

    [Fact]
    public void Create_ValidRequest_PassesValidation()
    {
        var result = _createValidator.TestValidate(new CreateLeaveRequestRequest(
            EntityBuilder.Employee1Id,
            EntityBuilder.AnnualLeaveId,
            new DateOnly(2026, 1, 10),
            new DateOnly(2026, 1, 12),
            "Family event"));
        result.ShouldNotHaveAnyValidationErrors();
    }

    [Fact]
    public void Create_InvalidDateRange_FailsValidation()
    {
        var result = _createValidator.TestValidate(new CreateLeaveRequestRequest(
            EntityBuilder.Employee1Id,
            EntityBuilder.AnnualLeaveId,
            new DateOnly(2026, 1, 12),
            new DateOnly(2026, 1, 10),
            "Family event"));
        result.ShouldHaveValidationErrorFor(x => x.ToDate);
    }

    [Fact]
    public void Update_NullFields_PassesValidation()
    {
        var result = _updateValidator.TestValidate(new UpdateLeaveRequestRequest(null, null, null, null, null, null));
        result.ShouldNotHaveAnyValidationErrors();
    }

    [Fact]
    public void Update_InvalidDateRange_FailsValidation()
    {
        var result = _updateValidator.TestValidate(new UpdateLeaveRequestRequest(
            null,
            null,
            new DateOnly(2026, 1, 12),
            new DateOnly(2026, 1, 10),
            null,
            null));
        result.ShouldHaveValidationErrorFor(x => x.ToDate);
    }
}
